sudo: required
dist: trusty

# Only build master and release tags
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# Choose a lightweight base image; we provide our own build tools.
language:
  c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

services:
  - docker

env:
  global:
    - RUN_INTEGRATION_TESTS=1
    - STACK_ARGS=""

  matrix:
    - DOCKER_VERSION="1.12.3-0~trusty"              GHCVER=7.10
    - DOCKER_VERSION="1.13.1-0~ubuntu-trusty"       GHCVER=7.10
    - DOCKER_VERSION="17.05.0~ce-0~ubuntu-trusty"   GHCVER=7.10

    - DOCKER_VERSION="1.12.3-0~trusty"              GHCVER=8.0
    - DOCKER_VERSION="1.13.1-0~ubuntu-trusty"       GHCVER=8.0
    - DOCKER_VERSION="17.05.0~ce-0~ubuntu-trusty"   GHCVER=8.0

    - DOCKER_VERSION="1.12.3-0~trusty"              GHCVER=8.0.2
    - DOCKER_VERSION="1.13.1-0~ubuntu-trusty"       GHCVER=8.0.2
    - DOCKER_VERSION="17.05.0~ce-0~ubuntu-trusty"   GHCVER=8.0.2

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
  # Upgrade docker to 1.12.3.0
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=$DOCKER_VERSION

install:
  - mkdir -p "$HOME"/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - export STACK_YAML=stack-$GHCVER.yaml
  # install Stack
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
  - export PATH=$(stack path --local-install-root):$PATH
  - stack --version

script:
  - stack setup
  - stack update
  - stack build
  - stack test

